"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarClock, CheckCircle2, LocateFixed, MapPin, Paperclip, Send } from "lucide-react";
import { Button, Feedback } from "@kaila/ui";
import styles from "./page.module.css";

type Reference = { id: number; name: string };
type Step = 1 | 2 | 3;

export default function PostJobPage() {
  const [step, setStep] = useState<Step>(1); const [categories, setCategories] = useState<Reference[]>([]); const [areas, setAreas] = useState<Reference[]>([]);
  const [status, setStatus] = useState<"loading" | "ready" | "saving" | "success" | "error">("loading"); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ title: "", description: "", categoryId: "", areaId: "", scheduleType: "asap", scheduledAt: "", budgetMin: "", budgetMax: "", addressLabel: "", latitude: "", longitude: "" });
  useEffect(() => { void fetch("/api/v1/marketplace/reference-data").then(async response => { if (!response.ok) throw new Error(); const body = await response.json() as { data: { categories: Reference[]; areas: Reference[] } }; setCategories(body.data.categories); setAreas(body.data.areas); const requestedCategory = new URLSearchParams(window.location.search).get("categoryId"); if (requestedCategory && body.data.categories.some(category => String(category.id) === requestedCategory)) setForm(current => ({ ...current, categoryId: requestedCategory })); setStatus("ready"); }).catch(() => setStatus("error")); }, []);
  function field(name: keyof typeof form, value: string) { setForm(current => ({ ...current, [name]: value })); }
  function locate() { if (!navigator.geolocation) { setMessage("Location is not available. Choose your area and add a nearby landmark instead."); return; } setMessage("Finding your location…"); navigator.geolocation.getCurrentPosition(position => { field("latitude", String(position.coords.latitude)); field("longitude", String(position.coords.longitude)); setMessage("Location pinned. Providers only see your area until you hire."); }, () => setMessage("Location permission was denied. You can continue with an area and landmark."), { timeout: 8000, enableHighAccuracy: false }); }
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 3) { setStep((step + 1) as Step); return; } setStatus("saving"); const payload = { title: form.title, description: form.description, categoryId: Number(form.categoryId), areaId: Number(form.areaId), scheduleType: form.scheduleType, scheduledAt: form.scheduleType === "scheduled" ? new Date(form.scheduledAt).toISOString() : null, budgetMinCentavos: form.budgetMin ? Math.round(Number(form.budgetMin) * 100) : null, budgetMaxCentavos: form.budgetMax ? Math.round(Number(form.budgetMax) * 100) : null, addressLabel: form.addressLabel || null, latitude: form.latitude ? Number(form.latitude) : null, longitude: form.longitude ? Number(form.longitude) : null };
    try { const created = await fetch("/api/v1/jobs", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(payload) }); if (!created.ok) throw new Error(); const body = await created.json() as { data: { id: string } }; const posted = await fetch(`/api/v1/jobs/${body.data.id}/post`, { method: "POST" }); if (!posted.ok) throw new Error(); setStatus("success"); } catch { setStatus("error"); setMessage("Your job could not be posted. Your details are still here—check your connection and try again."); }
  }
  if (status === "loading") return <main className={styles.shell}><div className={styles.skeleton} aria-label="Loading job form" /></main>;
  if (status === "success") return <main className={styles.shell}><section className={styles.success}><CheckCircle2 aria-hidden="true" /><h1>Your job is posted</h1><p>We’re alerting matching providers nearby.</p><Button onClick={() => location.assign("/home")}>Back to Home</Button></section></main>;
  return <main className={styles.shell}><header><Link href="/home" aria-label="Back to home"><ArrowLeft aria-hidden="true" /></Link><div><span>Step {step} of 3</span><progress value={step} max="3">{step} of 3</progress></div></header>
    <form onSubmit={submit}><section className={styles.card}>{step === 1 && <><p className={styles.eyebrow}>Tell us what you need</p><h1>What can we help with?</h1><label>Service<select required value={form.categoryId} onChange={e => field("categoryId", e.target.value)}><option value="">Choose a service</option>{categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Short title<input required maxLength={120} value={form.title} onChange={e => field("title", e.target.value)} placeholder="Fix a leaking kitchen tap" /></label><label>What needs to be done?<textarea required minLength={10} maxLength={3000} value={form.description} onChange={e => field("description", e.target.value)} placeholder="Add the details a provider needs to understand the job." /></label></>}
      {step === 2 && <><p className={styles.eyebrow}><MapPin aria-hidden="true" /> Nearby help</p><h1>Where is the job?</h1><label>Area<select required value={form.areaId} onChange={e => field("areaId", e.target.value)}><option value="">Choose your area</option>{areas.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Landmark or address<input value={form.addressLabel} maxLength={180} onChange={e => field("addressLabel", e.target.value)} placeholder="Shown only after you hire" /></label><Button type="button" variant="secondary" onClick={locate}><LocateFixed aria-hidden="true" /> Pin my location</Button>{message && <Feedback kind="info" title="Location">{message}</Feedback>}<p className={styles.privacy}>Providers see only your selected area before you hire. Your pin and address stay private.</p></>}
      {step === 3 && <><p className={styles.eyebrow}><CalendarClock aria-hidden="true" /> Timing and budget</p><h1>When do you need help?</h1><div className={styles.choices}><label><input type="radio" name="schedule" checked={form.scheduleType === "asap"} onChange={() => field("scheduleType", "asap")} /> As soon as possible</label><label><input type="radio" name="schedule" checked={form.scheduleType === "scheduled"} onChange={() => field("scheduleType", "scheduled")} /> Choose a date</label></div>{form.scheduleType === "scheduled" && <label>Date and time<input required type="datetime-local" value={form.scheduledAt} onChange={e => field("scheduledAt", e.target.value)} /></label>}<div className={styles.budget}><label>Budget from (₱)<input type="number" min="0" value={form.budgetMin} onChange={e => field("budgetMin", e.target.value)} /></label><label>Budget to (₱)<input type="number" min={form.budgetMin || "0"} value={form.budgetMax} onChange={e => field("budgetMax", e.target.value)} /></label></div><p className={styles.optional}><Paperclip aria-hidden="true" /> Photos can be added from your Jobs page after saving the draft.</p></>}
      {status === "error" && <Feedback kind="error" title="We couldn’t continue">{message || "Reload the page and try again."}</Feedback>}</section><footer>{step > 1 && <Button type="button" variant="secondary" onClick={() => setStep((step - 1) as Step)}>Back</Button>}<Button type="submit" disabled={status === "saving"}>{step === 3 ? <><Send aria-hidden="true" /> {status === "saving" ? "Posting…" : "Post Job"}</> : "Continue"}</Button></footer></form></main>;
}
