<?php

use App\Http\Controllers\AdminDisputeController;
use App\Http\Controllers\AdminMarketplaceController;
use App\Http\Controllers\AdminPhaseNineController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\MobileSessionController;
use App\Http\Controllers\Auth\PasswordRecoveryController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Auth\RegistrationConfigController;
use App\Http\Controllers\Auth\SessionStatusController;
use App\Http\Controllers\Auth\SocialAuthenticationController;
use App\Http\Controllers\CallController;
use App\Http\Controllers\CommunityController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\CurrentUserController;
use App\Http\Controllers\DirectConversationController;
use App\Http\Controllers\DurableNotificationController;
use App\Http\Controllers\JobAssetController;
use App\Http\Controllers\JobLifecycleController;
use App\Http\Controllers\KatabangController;
use App\Http\Controllers\MarketplaceProfileController;
use App\Http\Controllers\MessageAssetController;
use App\Http\Controllers\NotificationPreferenceController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\OpportunityController;
use App\Http\Controllers\ProfileAssetController;
use App\Http\Controllers\ProviderCredentialController;
use App\Http\Controllers\PushDeviceController;
use App\Http\Controllers\RealtimeTicketController;
use App\Http\Controllers\ReferenceDataController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\ServiceJobController;
use App\Http\Controllers\TravelController;
use App\Http\Controllers\UserSessionController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/auth/csrf', fn () => response()->noContent());

Route::middleware('throttle:registration')->post('/auth/register', RegisteredUserController::class);
Route::get('/auth/registration-config', RegistrationConfigController::class);
Route::get('/auth/session-status', SessionStatusController::class);
Route::get('/marketplace/reference-data', ReferenceDataController::class);
Route::middleware('throttle:login')->post('/auth/login', [AuthenticatedSessionController::class, 'store']);
Route::middleware('throttle:login')->get('/auth/social/{provider}/redirect', [SocialAuthenticationController::class, 'redirect']);
Route::get('/auth/social/{provider}/callback', [SocialAuthenticationController::class, 'callback']);
Route::middleware('throttle:login')->post('/auth/mobile/login', [MobileSessionController::class, 'store']);
Route::middleware('throttle:login')->post('/auth/mobile/refresh', [MobileSessionController::class, 'refresh']);
Route::middleware('throttle:password-recovery')->group(function (): void {
    Route::post('/auth/password/forgot', [PasswordRecoveryController::class, 'requestLink']);
    Route::post('/auth/password/reset', [PasswordRecoveryController::class, 'reset']);
});

Route::middleware('mobile.auth')->group(function (): void {
    Route::get('/auth/mobile/me', [MobileSessionController::class, 'me']);
    Route::post('/auth/mobile/logout', [MobileSessionController::class, 'destroyCurrent']);
    Route::get('/auth/mobile/sessions', [MobileSessionController::class, 'index']);
    Route::delete('/auth/mobile/sessions/{sessionId}', [MobileSessionController::class, 'destroy']);
    Route::post('/auth/mobile/realtime-ticket', [RealtimeTicketController::class, 'mobile']);
    Route::get('/auth/mobile/notification-preferences', [NotificationPreferenceController::class, 'show']);
    Route::put('/auth/mobile/notification-preferences', [NotificationPreferenceController::class, 'update']);
    Route::get('/auth/mobile/marketplace-profile', [MarketplaceProfileController::class, 'show']);
    Route::put('/auth/mobile/active-mode', [MarketplaceProfileController::class, 'mode']);
    Route::put('/auth/mobile/client-profile', [MarketplaceProfileController::class, 'client']);
    Route::put('/auth/mobile/provider-profile', [MarketplaceProfileController::class, 'provider']);
    Route::post('/auth/mobile/profile-assets', [ProfileAssetController::class, 'store']);
    Route::post('/auth/mobile/provider-credentials', [ProviderCredentialController::class, 'store']);
    Route::get('/auth/mobile/jobs', [ServiceJobController::class, 'index']);
    Route::post('/auth/mobile/jobs', [ServiceJobController::class, 'store']);
    Route::get('/auth/mobile/jobs/{serviceJob}', [ServiceJobController::class, 'show']);
    Route::put('/auth/mobile/jobs/{serviceJob}', [ServiceJobController::class, 'update']);
    Route::post('/auth/mobile/jobs/{serviceJob}/post', [ServiceJobController::class, 'post']);
    Route::post('/auth/mobile/jobs/{serviceJob}/assets', [JobAssetController::class, 'store']);
    Route::get('/auth/mobile/opportunities', [OpportunityController::class, 'index']);
    Route::put('/auth/mobile/opportunities/{opportunity}', [OpportunityController::class, 'decide']);
    Route::get('/auth/mobile/jobs/{serviceJob}/offers', [OfferController::class, 'index']);
    Route::post('/auth/mobile/jobs/{serviceJob}/offers', [OfferController::class, 'store']);
    Route::get('/auth/mobile/offers/{offerThread}', [OfferController::class, 'show']);
    Route::post('/auth/mobile/offers/{offerThread}/revisions', [OfferController::class, 'revise']);
    Route::post('/auth/mobile/offers/{offerThread}/withdraw', [OfferController::class, 'withdraw']);
    Route::post('/auth/mobile/offers/{offerThread}/decline', [OfferController::class, 'decline']);
    Route::post('/auth/mobile/jobs/{serviceJob}/select-offer', [OfferController::class, 'select']);
    Route::get('/auth/mobile/jobs/{serviceJob}/conversation', [ConversationController::class, 'show']);
    Route::post('/auth/mobile/jobs/{serviceJob}/conversation/messages', [ConversationController::class, 'send']);
    Route::post('/auth/mobile/messages/{conversationMessage}/assets', [MessageAssetController::class, 'store']);
    Route::get('/auth/mobile/message-assets/{messageAsset}', [MessageAssetController::class, 'show']);
    Route::put('/auth/mobile/jobs/{serviceJob}/conversation/read', [ConversationController::class, 'read']);
    Route::put('/auth/mobile/jobs/{serviceJob}/conversation/typing', [ConversationController::class, 'typing']);
    Route::get('/auth/mobile/jobs/{serviceJob}/travel', [TravelController::class, 'show']);
    Route::post('/auth/mobile/jobs/{serviceJob}/travel/start', [TravelController::class, 'start']);
    Route::post('/auth/mobile/jobs/{serviceJob}/travel/location', [TravelController::class, 'update']);
    Route::post('/auth/mobile/jobs/{serviceJob}/travel/stop', [TravelController::class, 'stop']);
    Route::get('/auth/mobile/jobs/{serviceJob}/work', [JobLifecycleController::class, 'show']);
    Route::post('/auth/mobile/jobs/{serviceJob}/work/start', [JobLifecycleController::class, 'start']);
    Route::post('/auth/mobile/jobs/{serviceJob}/completion', [JobLifecycleController::class, 'submit']);
    Route::post('/auth/mobile/completions/{completionSubmission}/evidence', [JobLifecycleController::class, 'evidence']);
    Route::post('/auth/mobile/jobs/{serviceJob}/completion/confirm', [JobLifecycleController::class, 'confirm']);
    Route::post('/auth/mobile/jobs/{serviceJob}/completion/revision', [JobLifecycleController::class, 'revision']);
    Route::post('/auth/mobile/jobs/{serviceJob}/cancel', [JobLifecycleController::class, 'cancel']);
    Route::post('/auth/mobile/jobs/{serviceJob}/disputes', [JobLifecycleController::class, 'dispute']);
    Route::post('/auth/mobile/disputes/{disputeCase}/evidence', [JobLifecycleController::class, 'disputeEvidence']);
    Route::get('/auth/mobile/jobs/{serviceJob}/reviews', [ReviewController::class, 'index']);
    Route::post('/auth/mobile/jobs/{serviceJob}/reviews', [ReviewController::class, 'store']);
    Route::post('/auth/mobile/disputes/{disputeCase}/appeal', [AdminDisputeController::class, 'appeal']);
    Route::get('/auth/mobile/notifications', [DurableNotificationController::class, 'index']);
    Route::put('/auth/mobile/notifications/{notification}/read', [DurableNotificationController::class, 'read']);
    Route::delete('/auth/mobile/notifications/{notification}', [DurableNotificationController::class, 'clear']);
    Route::post('/auth/mobile/push-devices', [PushDeviceController::class, 'store']);
    Route::delete('/auth/mobile/push-devices/{pushDevice}', [PushDeviceController::class, 'destroy']);
    Route::get('/auth/mobile/direct-conversations', [DirectConversationController::class, 'index']);
    Route::post('/auth/mobile/direct-conversations', [DirectConversationController::class, 'store']);
    Route::get('/auth/mobile/direct-conversations/{directConversation}', [DirectConversationController::class, 'show']);
    Route::post('/auth/mobile/direct-conversations/{directConversation}/accept', [DirectConversationController::class, 'accept']);
    Route::post('/auth/mobile/direct-conversations/{directConversation}/messages', [DirectConversationController::class, 'send']);
    Route::post('/auth/mobile/calls', [CallController::class, 'store']);
    Route::post('/auth/mobile/calls/{callSession}/transition', [CallController::class, 'transition']);
    Route::post('/auth/mobile/community', [CommunityController::class, 'store']);
    Route::put('/auth/mobile/community/{communityPost}/helpful', [CommunityController::class, 'react']);
    Route::post('/auth/mobile/katabang', KatabangController::class);
});

Route::middleware('auth')->group(function (): void {
    Route::get('/me', CurrentUserController::class);
    Route::get('/providers', [MarketplaceProfileController::class, 'discover']);
    Route::get('/providers/{providerProfile}', [MarketplaceProfileController::class, 'publicProfile']);
    Route::get('/community', [CommunityController::class, 'index']);
    Route::get('/profile-assets/{profileAsset}', [ProfileAssetController::class, 'show']);
    Route::post('/auth/logout', [AuthenticatedSessionController::class, 'destroy']);
    Route::post('/auth/logout-all', [AuthenticatedSessionController::class, 'destroyAll']);
    Route::get('/me/sessions', [UserSessionController::class, 'index']);
    Route::delete('/me/sessions/{sessionId}', [UserSessionController::class, 'destroy']);
    Route::post('/realtime/ticket', [RealtimeTicketController::class, 'browser']);
    Route::get('/me/notification-preferences', [NotificationPreferenceController::class, 'show']);
    Route::put('/me/notification-preferences', [NotificationPreferenceController::class, 'update']);
    Route::get('/me/marketplace-profile', [MarketplaceProfileController::class, 'show']);
    Route::put('/me/active-mode', [MarketplaceProfileController::class, 'mode']);
    Route::put('/me/client-profile', [MarketplaceProfileController::class, 'client']);
    Route::put('/me/provider-profile', [MarketplaceProfileController::class, 'provider']);
    Route::post('/me/profile-assets', [ProfileAssetController::class, 'store']);
    Route::post('/me/provider-credentials', [ProviderCredentialController::class, 'store']);
    Route::get('/jobs', [ServiceJobController::class, 'index']);
    Route::post('/jobs', [ServiceJobController::class, 'store']);
    Route::get('/jobs/{serviceJob}', [ServiceJobController::class, 'show']);
    Route::put('/jobs/{serviceJob}', [ServiceJobController::class, 'update']);
    Route::post('/jobs/{serviceJob}/post', [ServiceJobController::class, 'post']);
    Route::post('/jobs/{serviceJob}/assets', [JobAssetController::class, 'store']);
    Route::get('/opportunities', [OpportunityController::class, 'index']);
    Route::put('/opportunities/{opportunity}', [OpportunityController::class, 'decide']);
    Route::get('/jobs/{serviceJob}/offers', [OfferController::class, 'index']);
    Route::post('/jobs/{serviceJob}/offers', [OfferController::class, 'store']);
    Route::get('/offers/{offerThread}', [OfferController::class, 'show']);
    Route::post('/offers/{offerThread}/revisions', [OfferController::class, 'revise']);
    Route::post('/offers/{offerThread}/withdraw', [OfferController::class, 'withdraw']);
    Route::post('/offers/{offerThread}/decline', [OfferController::class, 'decline']);
    Route::post('/jobs/{serviceJob}/select-offer', [OfferController::class, 'select']);
    Route::get('/jobs/{serviceJob}/conversation', [ConversationController::class, 'show']);
    Route::post('/jobs/{serviceJob}/conversation/messages', [ConversationController::class, 'send']);
    Route::post('/messages/{conversationMessage}/assets', [MessageAssetController::class, 'store']);
    Route::get('/message-assets/{messageAsset}', [MessageAssetController::class, 'show']);
    Route::put('/jobs/{serviceJob}/conversation/read', [ConversationController::class, 'read']);
    Route::put('/jobs/{serviceJob}/conversation/typing', [ConversationController::class, 'typing']);
    Route::get('/jobs/{serviceJob}/travel', [TravelController::class, 'show']);
    Route::post('/jobs/{serviceJob}/travel/start', [TravelController::class, 'start']);
    Route::post('/jobs/{serviceJob}/travel/location', [TravelController::class, 'update']);
    Route::post('/jobs/{serviceJob}/travel/stop', [TravelController::class, 'stop']);
    Route::get('/jobs/{serviceJob}/work', [JobLifecycleController::class, 'show']);
    Route::post('/jobs/{serviceJob}/work/start', [JobLifecycleController::class, 'start']);
    Route::post('/jobs/{serviceJob}/completion', [JobLifecycleController::class, 'submit']);
    Route::post('/completions/{completionSubmission}/evidence', [JobLifecycleController::class, 'evidence']);
    Route::post('/jobs/{serviceJob}/completion/confirm', [JobLifecycleController::class, 'confirm']);
    Route::post('/jobs/{serviceJob}/completion/revision', [JobLifecycleController::class, 'revision']);
    Route::post('/jobs/{serviceJob}/cancel', [JobLifecycleController::class, 'cancel']);
    Route::post('/jobs/{serviceJob}/disputes', [JobLifecycleController::class, 'dispute']);
    Route::post('/disputes/{disputeCase}/evidence', [JobLifecycleController::class, 'disputeEvidence']);
    Route::post('/disputes/{disputeCase}/appeal', [AdminDisputeController::class, 'appeal']);
    Route::get('/jobs/{serviceJob}/reviews', [ReviewController::class, 'index']);
    Route::post('/jobs/{serviceJob}/reviews', [ReviewController::class, 'store']);
    Route::get('/notifications', [DurableNotificationController::class, 'index']);
    Route::put('/notifications/{notification}/read', [DurableNotificationController::class, 'read']);
    Route::delete('/notifications/{notification}', [DurableNotificationController::class, 'clear']);
    Route::post('/push-devices', [PushDeviceController::class, 'store']);
    Route::delete('/push-devices/{pushDevice}', [PushDeviceController::class, 'destroy']);
    Route::get('/direct-conversations', [DirectConversationController::class, 'index']);
    Route::post('/direct-conversations', [DirectConversationController::class, 'store']);
    Route::get('/direct-conversations/{directConversation}', [DirectConversationController::class, 'show']);
    Route::post('/direct-conversations/{directConversation}/accept', [DirectConversationController::class, 'accept']);
    Route::post('/direct-conversations/{directConversation}/messages', [DirectConversationController::class, 'send']);
    Route::post('/calls', [CallController::class, 'store']);
    Route::post('/calls/{callSession}/transition', [CallController::class, 'transition']);
    Route::post('/community', [CommunityController::class, 'store']);
    Route::put('/community/{communityPost}/helpful', [CommunityController::class, 'react']);
    Route::post('/katabang', KatabangController::class);
    Route::middleware('admin')->prefix('admin/marketplace')->group(function (): void {
        Route::get('/cases', [AdminDisputeController::class, 'index']);
        Route::get('/cases/{disputeCase}', [AdminDisputeController::class, 'show']);
        Route::post('/cases/{disputeCase}/decision', [AdminDisputeController::class, 'decide']);
        Route::get('/review-queue', [AdminMarketplaceController::class, 'queue']);
        Route::post('/categories', [AdminMarketplaceController::class, 'category']);
        Route::put('/categories/{serviceCategory}', [AdminMarketplaceController::class, 'category']);
        Route::post('/areas', [AdminMarketplaceController::class, 'area']);
        Route::put('/areas/{area}', [AdminMarketplaceController::class, 'area']);
        Route::put('/providers/{providerProfile}/status', [AdminMarketplaceController::class, 'provider']);
        Route::put('/assets/{profileAsset}/scan', [AdminMarketplaceController::class, 'asset']);
        Route::put('/message-assets/{messageAsset}/scan', [MessageAssetController::class, 'review']);
        Route::put('/credentials/{providerCredential}/review', [AdminMarketplaceController::class, 'credential']);
        Route::get('/analytics', [AdminPhaseNineController::class, 'analytics']);
        Route::get('/operations-validation', [AdminPhaseNineController::class, 'operations']);
    });
});

Route::fallback(function (Request $request) {
    return response()->json([
        'error' => [
            'code' => 'NOT_FOUND',
            'message' => 'The requested endpoint was not found.',
            'fields' => (object) [],
        ],
    ], 404);
});
