/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { FormEvent, useState } from "react";
import { ArrowLeft, Clock3, PhilippinePeso, ShieldCheck } from "lucide-react";
import { Button, Feedback, TextField } from "@kaila/ui";
import styles from "../../offers.module.css";

export default function MakeOfferPage({params}:{params:Promise<{jobId:string}>}) {
  const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");const data=new FormData(event.currentTarget);const {jobId}=await params;const response=await fetch(`/api/v1/jobs/${jobId}/offers`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amountCentavos:Math.round(Number(data.get("amount"))*100),availabilityText:data.get("availability"),estimatedDurationText:data.get("duration")||null,scope:data.get("scope"),message:data.get("message")||null,expiresAt:null})});setStatus(response.ok?"success":"error");}
  if(status==="success")return <main className={styles.shell}><section className={styles.success}><ShieldCheck aria-hidden="true"/><h1>Offer sent</h1><p>The client can now compare your price, timing, and experience. We’ll let you know when they respond.</p><Button onClick={()=>location.assign("/opportunities")}>Back to opportunities</Button></section></main>;
  return <main className={styles.shell}><a className={styles.back} href="/opportunities"><ArrowLeft aria-hidden="true"/>Opportunities</a><header><p>One clear proposal</p><h1>Make an offer</h1><span>Your terms become part of an immutable negotiation history.</span></header>{status==="error"&&<Feedback kind="error" title="Your offer wasn’t sent">Review your details and try again.</Feedback>}<form className={styles.form} onSubmit={event=>void submit(event)}><TextField id="offer-amount" label="Price in pesos" name="amount" type="number" min="1" step="0.01" required/><TextField id="offer-availability" label="When can you start?" name="availability" placeholder="Today at 2 PM" required/><TextField id="offer-duration" label="Estimated duration" name="duration" placeholder="About two hours"/><label>What’s included?<textarea name="scope" minLength={1} maxLength={2000} required/></label><label>Message to the client <span>Optional</span><textarea name="message" maxLength={1000}/></label><div className={styles.summary}><PhilippinePeso aria-hidden="true"/><p><strong>Price stays exact</strong><span>The client accepts this specific revision.</span></p><Clock3 aria-hidden="true"/><p><strong>You can revise later</strong><span>Earlier versions remain visible to both of you.</span></p></div><Button type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Send Offer"}</Button></form></main>;
}
