/* eslint-disable @next/next/no-img-element */
"use client";
import { useCallback, useEffect, useState } from "react";
import { BriefcaseBusiness, CalendarClock, MapPin, RefreshCw, Star, WalletCards } from "lucide-react";
import { Button, Feedback } from "@kaila/ui";
import { MarketplaceNavigation } from "../../components/marketplace-navigation";
import styles from "./page.module.css";
import { useRealtimeInvalidation } from "../use-realtime-invalidation";
import { ServiceCategoryIcon } from "../../components/service-category-icon";
import { JobRequestLocation } from "../../components/job-request-location";
type Opportunity = { id:number; jobId:string; state:string; title:string; description:string; client:{displayName:string;avatarUrl:string|null;rating:string|null;reviewCount:number}; area:{name:string}; category:{name:string;icon:string}; scheduleType:string; scheduledAt:string|null; budgetMinCentavos:number|null; budgetMaxCentavos:number|null; approximateAddress:string; approximateLocation:{latitude:number;longitude:number}|null; attachmentCount:number; offer:{id:string;status:string;latestRevisionNumber:number}|null };
export default function OpportunitiesPage() {
  const [items,setItems]=useState<Opportunity[]>([]); const [status,setStatus]=useState<"loading"|"ready"|"error">("loading");
  const load=useCallback(async()=>{try{const response=await fetch("/api/v1/opportunities",{cache:"no-store"});if(!response.ok)throw new Error();const body=await response.json() as {data:Opportunity[]};setItems(body.data);setStatus("ready");}catch{setStatus("error");}},[]);
  useRealtimeInvalidation(()=>void load(),event=>["opportunity.matched","opportunity.updated","job.updated","job.media.updated","job.state.changed","offer.created","offer.revised","offer.selected","offer.rejected","offer.withdrawn","notification.created"].includes(event.type));
  useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const reconcile=()=>void load();window.addEventListener("online",reconcile);return()=>{window.clearTimeout(initial);window.removeEventListener("online",reconcile);};},[load]);
  async function dismiss(id:number){const response=await fetch(`/api/v1/opportunities/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision:"dismissed"})});if(response.ok)setItems(current=>current.filter(row=>row.id!==id));else setStatus("error");}
  return <main className={styles.shell}><header><div><p>Provider mode</p><h1>Opportunities</h1></div><Button variant="secondary" onClick={()=>void load()}><RefreshCw aria-hidden="true"/>Refresh</Button></header>
    {status==="loading"&&<div className={styles.skeletons} aria-label="Loading opportunities"><span/><span/></div>}{status==="error"&&<Feedback kind="error" title="We couldn’t refresh opportunities">Check your connection, then try again.</Feedback>}
    {status==="ready"&&items.length===0&&<section className={styles.empty}><BriefcaseBusiness aria-hidden="true"/><h2>No nearby jobs right now</h2><p>We’ll show jobs that match your services, area, and availability.</p><Button onClick={()=>void load()}>Check again</Button></section>}
    <section className={styles.list}>{items.map(item=><article key={item.id}><div className={styles.client}><span className={styles.avatar}>{item.client.avatarUrl?<img src={item.client.avatarUrl} alt={`${item.client.displayName} profile`} />:item.client.displayName[0]}</span><div><small>Posted by</small><strong>{item.client.displayName}</strong><span className={styles.reputation}><Star aria-hidden="true"/>{reputation(item.client.rating,item.client.reviewCount)}</span></div></div><div className={styles.title}><span className={styles.category}><ServiceCategoryIcon icon={item.category.icon} aria-hidden="true"/>{item.category.name}</span>{item.offer&&<strong className={styles.offerBadge}>Offer sent · Revision {item.offer.latestRevisionNumber}</strong>}<h2>{item.title}</h2></div><p>{item.description}</p><JobRequestLocation opportunityId={item.id} address={item.approximateAddress} location={item.approximateLocation} /><dl><div><MapPin aria-hidden="true"/><dt>Area</dt><dd>{item.area.name}</dd></div><div><CalendarClock aria-hidden="true"/><dt>When</dt><dd>{item.scheduleType==="asap"?"As soon as possible":new Date(item.scheduledAt??"").toLocaleString()}</dd></div><div><WalletCards aria-hidden="true"/><dt>Budget</dt><dd>{money(item.budgetMinCentavos,item.budgetMaxCentavos)}</dd></div></dl><p className={styles.privacy}>This location is approximate. Exact coordinates stay private until hiring.</p><div className={styles.actions}>{!item.offer&&<Button variant="secondary" onClick={()=>void dismiss(item.id)}>Dismiss</Button>}<Button onClick={()=>location.assign(`/opportunities/${item.jobId}`)}>{item.offer?"View request & offer":"View Job"}</Button></div></article>)}</section>
    <MarketplaceNavigation active="opportunities" />
  </main>;
}
function money(min:number|null,max:number|null){if(min===null&&max===null)return "Open to offers";const peso=(value:number|null)=>value===null?"—":`₱${(value/100).toLocaleString()}`;return `${peso(min)} – ${peso(max)}`;}
function reputation(rating:string|null,count:number){return rating?`${Number(rating).toFixed(1)} · ${count} review${count===1?"":"s"}`:"New · No reviews yet";}
