"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, BarChart3, RefreshCw, ShieldCheck } from "lucide-react";
import styles from "../page.module.css";

type Analytics = { privacy: { minimumCohort: number; suppressed: boolean }; marketplace: { users: number; jobs: number; completedJobs: number; offers: number } | null; phaseNine: { directConversations: number; communityPosts: number; assistantInteractions: number; calls: number } };
type Operations = { status: string; checks: Record<string, boolean>; checkedAt: string };
export default function AnalyticsPage() {
  const [analytics, setAnalytics] = useState<Analytics | null>(null); const [operations, setOperations] = useState<Operations | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = useCallback(async () => { try { const [a, o] = await Promise.all([fetch("/api/v1/admin/marketplace/analytics", { credentials: "include" }), fetch("/api/v1/admin/marketplace/operations-validation", { credentials: "include" })]); if (!a.ok || !o.ok) throw new Error(); setAnalytics(((await a.json()) as { data: Analytics }).data); setOperations(((await o.json()) as { data: Operations }).data); setState("ready"); } catch { setState("error"); } }, []);
  useEffect(() => { void Promise.all([fetch("/api/v1/admin/marketplace/analytics", { credentials: "include" }), fetch("/api/v1/admin/marketplace/operations-validation", { credentials: "include" })]).then(async ([a, o]) => { if (!a.ok || !o.ok) throw new Error(); setAnalytics(((await a.json()) as { data: Analytics }).data); setOperations(((await o.json()) as { data: Operations }).data); setState("ready"); }).catch(() => setState("error")); }, []);
  return <main className={styles.page}><header><div><p>KAILA ADMINISTRATION</p><h1>Marketplace health</h1></div><button onClick={() => void load()}><RefreshCw aria-hidden="true" />Refresh</button></header>{state === "loading" && <div className={styles.loading}>Loading aggregate healthâ€¦</div>}{state === "error" && <div className={styles.error}>Marketplace health could not be loaded.</div>}{state === "ready" && analytics && operations && <div className={styles.columns}><section><h2><BarChart3 aria-hidden="true" />Privacy-safe analytics</h2>{analytics.privacy.suppressed ? <p className={styles.empty}>Marketplace metrics are hidden until at least {analytics.privacy.minimumCohort} users are included.</p> : <div className={styles.actions}><article><h3>{analytics.marketplace?.jobs}</h3><p>Jobs</p></article><article><h3>{analytics.marketplace?.completedJobs}</h3><p>Completed</p></article><article><h3>{analytics.marketplace?.offers}</h3><p>Offers</p></article></div>}<article><h3>Optional modules</h3><p>{analytics.phaseNine.directConversations} conversations Â· {analytics.phaseNine.communityPosts} posts Â· {analytics.phaseNine.assistantInteractions} assistant requests Â· {analytics.phaseNine.calls} calls</p></article></section><section><h2><Activity aria-hidden="true" />Operations validation</h2><article><h3>{operations.status === "ready" ? <><ShieldCheck aria-hidden="true" /> Ready</> : "Needs attention"}</h3>{Object.entries(operations.checks).map(([name, passing]) => <p key={name}>{passing ? "Pass" : "Attention"} â€” {name}</p>)}</article></section></div>}</main>;
}
