"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, CalendarClock, MapPin, Star } from "lucide-react";
import { Feedback } from "@kaila/ui";
import styles from "../providers.module.css";

type Item={id:number;name:string}; type Provider={id:number;displayName:string;bio:string;yearsExperience:number;rating:number|null;reviewCount:number;completedJobs:number;verified:boolean;services:Item[];serviceAreas:Item[];availability:{id:number;day_of_week:number;starts_at:string;ends_at:string}[];availabilityStatus:string;shopName:string|null;reviews:{id:string;rating:number;comment:string|null;publishedAt:string}[]};
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export default function ProviderProfilePage(){const {providerId}=useParams<{providerId:string}>();const [provider,setProvider]=useState<Provider|null>(null);const [error,setError]=useState(false);useEffect(()=>{void fetch(`/api/v1/providers/${providerId}`,{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();setProvider((await response.json() as {data:Provider}).data)}).catch(()=>setError(true))},[providerId]);if(error)return <main className={styles.shell}><Feedback kind="error" title="Provider unavailable">This profile may no longer be accepting requests.</Feedback></main>;if(!provider)return <main className={styles.shell}><p>Loading provider…</p></main>;return <main className={styles.shell}><header className={styles.header}><Link href="/providers" aria-label="Back to providers"><ArrowLeft/></Link><div><p>Provider profile</p><h1>{provider.displayName}</h1></div></header><section className={styles.card}><div className={styles.cardTop}><div className={styles.avatar}>{provider.displayName[0]}</div><div><h2>{provider.displayName}{provider.verified&&<BadgeCheck aria-label="Verified provider"/>}</h2><p>{provider.shopName||`${provider.yearsExperience} years of experience`}</p></div><span className={styles.available}>Available</span></div><p>{provider.bio}</p><div className={styles.metrics}><span><Star/>{provider.rating===null?"New":provider.rating.toFixed(1)} · {provider.reviewCount} reviews</span><span><BriefcaseBusiness/>{provider.completedJobs} completed jobs</span></div></section><section className={styles.card}><h2>Services offered</h2><div className={styles.services}>{provider.services.map(item=><span key={item.id}>{item.name}</span>)}</div><h2><MapPin/>Covered locations</h2><p>{provider.serviceAreas.map(item=>item.name).join(", ")}</p></section><section className={styles.card}><h2><CalendarClock/>Availability</h2>{provider.availability.map(slot=><p key={slot.id}>{days[slot.day_of_week]} · {slot.starts_at.slice(0,5)}–{slot.ends_at.slice(0,5)}</p>)}</section><section className={styles.card}><h2>Ratings and reviews</h2>{provider.reviews.length===0?<p>No published reviews yet.</p>:provider.reviews.map(review=><article key={review.id}><strong><Star/> {review.rating}.0</strong>{review.comment&&<p>{review.comment}</p>}<small>{review.publishedAt}</small></article>)}</section><Link className={styles.profileLink} href={`/post-job?providerId=${provider.id}&categoryId=${provider.services[0]?.id||""}`}>Request Service</Link><p className={styles.intro}>Personal phone numbers and contact details remain private. You can coordinate safely in KAILA after sending a request.</p></main>}
